import re

path = '/Users/nguyetpham/Desktop/WEBSITE/SPEAKING MOCK TESTS/test 3/test03-index.html'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

new_translations = [
    'Tôi là một người rất thích <strong style="color: #00b0f0;">2 Ngày 1 Đêm</strong>. Nó rất <strong style="color: #00b0f0;">mang tính giải trí</strong> và <strong style="color: #00b0f0;">hài hước</strong>. Nó giúp tôi <strong style="color: #00b0f0;">thư giãn sau khi học</strong> và <strong style="color: #00b0f0;">giảm căng thẳng</strong>.',
    'Tôi là một người rất thích <strong style="color: #00b0f0;">2 Ngày 1 Đêm</strong> vì nó vừa <strong style="color: #00b0f0;">mang tính giải trí</strong> vừa <strong style="color: #00b0f0;">lôi cuốn</strong>. Các thành viên trong chương trình <strong style="color: #00b0f0;">tham gia nhiều hoạt động thú vị</strong> và <strong style="color: #00b0f0;">đến thăm các địa điểm khác nhau</strong>. Việc xem chương trình giúp tôi <strong style="color: #00b0f0;">thư giãn sau một ngày bận rộn</strong>.',
    'Tôi <strong style="color: #00b0f0;">thích xem nó cùng với gia đình</strong> hơn. Chúng tôi có thể <strong style="color: #00b0f0;">cùng nhau cười đùa</strong> và <strong style="color: #00b0f0;">tận hưởng những khoảnh khắc hài hước</strong> trong chương trình. Đây là một cách hay để <strong style="color: #00b0f0;">dành thời gian chất lượng bên nhau</strong>.',
    'Tôi muốn <strong style="color: #00b0f0;">xem nó cùng gia đình hoặc bạn bè</strong> hơn. Việc cùng họ xem những hoạt động hài hước và các chuyến đi thú vị <strong style="color: #00b0f0;">khiến trải nghiệm trở nên thú vị hơn</strong>. Nó cũng cho chúng tôi cơ hội để <strong style="color: #00b0f0;">dành thời gian chất lượng bên nhau</strong> và <strong style="color: #00b0f0;">củng cố các mối quan hệ của chúng tôi</strong>.',
    'Một lợi ích là nó giúp tôi <strong style="color: #00b0f0;">thư giãn sau một ngày bận rộn</strong>. Một lợi ích khác là tôi có thể <strong style="color: #00b0f0;">học được nhiều điều mới</strong> từ chương trình. Nó vừa <strong style="color: #00b0f0;">mang tính giải trí</strong> vừa <strong style="color: #00b0f0;">mang tính giáo dục</strong>.',
    'Việc xem các chương trình trò chơi <strong style="color: #00b0f0;">mang lại cả lợi ích giải trí và giáo dục</strong>. Chúng giúp tôi <strong style="color: #00b0f0;">giải tỏa tâm trí</strong> và <strong style="color: #00b0f0;">cải thiện tâm trạng</strong>. Đồng thời, tôi có thể <strong style="color: #00b0f0;">thu thập được kiến thức hữu ích</strong> và <strong style="color: #00b0f0;">học được những sự thật thú vị về nhiều chủ đề khác nhau</strong>.',
    '<strong style="color: #00b0f0;">Vâng</strong>, tôi đã từng. Tôi thường <strong style="color: #00b0f0;">đi xe buýt để di chuyển quanh thành phố</strong>. Nó <strong style="color: #00b0f0;">dễ sử dụng</strong> và <strong style="color: #00b0f0;">có sẵn ở nhiều khu vực</strong>. Tôi thường <strong style="color: #00b0f0;">chọn nó cho những chuyến đi ngắn</strong>.',
    '<strong style="color: #00b0f0;">Vâng</strong>, tôi đã đi xe buýt nhiều lần. Đây là <strong style="color: #00b0f0;">một trong những phương tiện giao thông hợp túi tiền nhất</strong>, đặc biệt là đối với sinh viên và những người có ngân sách hạn hẹp.',
    '<strong style="color: #00b0f0;">Vâng</strong>, tôi nghĩ nó khá tốt. Có <strong style="color: #00b0f0;">nhiều tuyến xe buýt ở các thành phố lớn</strong>. Các xe buýt <strong style="color: #00b0f0;">chạy thường xuyên trong suốt cả ngày</strong>. Nhiều người <strong style="color: #00b0f0;">dựa vào chúng cho việc đi lại hàng ngày</strong>.',
    'Nhìn chung là <strong style="color: #00b0f0;">có</strong>. Dịch vụ xe buýt <strong style="color: #00b0f0;">đã cải thiện rất nhiều trong những năm gần đây</strong>. Chúng <strong style="color: #00b0f0;">dễ tiếp cận hơn</strong>, <strong style="color: #00b0f0;">giá cả phải chăng</strong>, và <strong style="color: #00b0f0;">thân thiện với môi trường</strong> hơn trước đây.',
    'Việc đi xe buýt có nhiều lợi ích. Nó giúp mọi người <strong style="color: #00b0f0;">tiết kiệm tiền</strong>. Nó có thể <strong style="color: #00b0f0;">giảm ùn tắc giao thông</strong> và <strong style="color: #00b0f0;">bảo vệ môi trường</strong>.',
    'Việc đi xe buýt có lợi về nhiều mặt. Nó cho phép mọi người <strong style="color: #00b0f0;">tiết kiệm tiền đi lại</strong> và giúp <strong style="color: #00b0f0;">giảm tình trạng kẹt xe</strong>. Hơn nữa, nó cũng là một cách thiết thực để <strong style="color: #00b0f0;">bảo vệ môi trường</strong>.',
    'À, nếu tôi phải <strong style="color: #ee0000;">đề xuất một diễn giả cho câu lạc bộ thanh niên của chúng tôi</strong>, tôi sẽ <strong style="color: #ee0000;">khuyên nên mời một vị chủ tịch công ty</strong>.<br/><br/>Đầu tiên, một vị chủ tịch công ty thường <strong style="color: #00b0f0;">có vốn kinh nghiệm sống phong phú</strong>. Họ <strong style="color: #00b0f0;">đã vượt qua nhiều thử thách trước khi thành công</strong>. Vì vậy, các thành viên có thể <strong style="color: #00b0f0;">học được những bài học quan trọng về cuộc sống và thành công</strong>.<br/><br/>Thứ hai, diễn giả có thể <strong style="color: #00b0f0;">truyền cảm hứng cho những người trẻ tuổi làm việc chăm chỉ và không bao giờ bỏ cuộc</strong>. Câu chuyện của họ có thể cho thấy rằng <strong style="color: #00b0f0;">thành công cần thời gian và nỗ lực</strong>. Vì vậy, các thành viên có thể <strong style="color: #00b0f0;">trở nên có động lực hơn</strong>.<br/><br/>Tôi sẽ không đề xuất <strong style="color: #70ad47;">mời một ca sĩ nổi tiếng</strong> bởi vì <strong style="color: #70ad47;">buổi nói chuyện có thể tập trung quá nhiều vào tính giải trí</strong>. Về việc mời <strong style="color: #7030a0;">một học sinh xuất sắc</strong>, nó ít phù hợp hơn bởi vì <strong style="color: #7030a0;">người đó có thể không có nhiều kinh nghiệm sống để chia sẻ</strong>.<br/><br/>Tóm lại, tôi tin rằng <strong style="color: #ee0000;">một chủ tịch công ty</strong> là lựa chọn tốt nhất cho tình huống này.',
    'À, nếu tôi phải <strong style="color: #ee0000;">đề xuất một diễn giả cho câu lạc bộ thanh niên của chúng tôi</strong>, tôi sẽ <strong style="color: #ee0000;">khuyên nên mời một vị chủ tịch công ty</strong>.<br/><br/>Đầu tiên, <strong style="color: #00b0f0;">đây là một lựa chọn mang tính giáo dục</strong> bởi vì các thành viên trong câu lạc bộ có thể <strong style="color: #00b0f0;">lắng nghe những trải nghiệm thực tế từ một doanh nhân thành đạt</strong>. Bên cạnh đó, họ có thể <strong style="color: #00b0f0;">học được những bài học giá trị về công việc và cuộc sống</strong>. Bằng cách này, họ có thể <strong style="color: #00b0f0;">thu thập được những kiến thức hữu ích cho tương lai</strong>.<br/><br/>Thứ hai, <strong style="color: #00b0f0;">nó có thể rất truyền cảm hứng</strong> bởi vì các sinh viên có thể <strong style="color: #00b0f0;">tìm hiểu về hành trình đi đến thành công của diễn giả</strong>. Hơn nữa, họ có thể <strong style="color: #00b0f0;">hiểu được tầm quan trọng của sự chăm chỉ và quyết tâm</strong>. Kết quả là, họ có thể <strong style="color: #00b0f0;">trở nên có động lực hơn</strong> để <strong style="color: #00b0f0;">đạt được mục tiêu của mình</strong>.<br/><br/>Tôi sẽ không đề xuất <strong style="color: #70ad47;">mời một ca sĩ nổi tiếng</strong> bởi vì <strong style="color: #70ad47;">buổi nói chuyện có thể tập trung nhiều hơn</strong> vào <strong style="color: #70ad47;">tính giải trí thay vì những bài học cuộc sống</strong>. Về việc mời <strong style="color: #7030a0;">một học sinh xuất sắc</strong>, nó ít phù hợp hơn bởi vì <strong style="color: #7030a0;">người đó có thể không có nhiều kinh nghiệm sống như những diễn giả khác</strong>.<br/><br/>Tóm lại, tôi tin rằng <strong style="color: #ee0000;">một chủ tịch công ty</strong> là lựa chọn tốt nhất cho tình huống này.',
    'Có một số <strong style="color: #ee0000;">bất lợi</strong> của việc <strong style="color: #ee0000;">nuôi giữ động vật trong vườn thú</strong>.<br/><br/>Một nhược điểm lớn là <strong style="color: #00b0f0;">động vật có thể phải đối mặt với việc thiếu không gian</strong>. Điều này là do <strong style="color: #00b0f0;">vườn thú thường nhỏ hơn nhiều so với môi trường sống tự nhiên</strong>. Kết quả là, động vật <strong style="color: #00b0f0;">có thể không có đủ không gian để tự do di chuyển xung quanh</strong>.<br/><br/>Một khía cạnh tiêu cực khác là <strong style="color: #00b0f0;">động vật có thể trải qua sự mất tự do</strong>. Điều này có nghĩa là chúng <strong style="color: #00b0f0;">không thể sống và di chuyển tự do trong môi trường hoang dã</strong>. Do đó, chúng có thể <strong style="color: #00b0f0;">cảm thấy căng thẳng hoặc không vui</strong>.<br/><br/>Một tác hại nữa là <strong style="color: #00b0f0;">động vật có thể bị thiếu kỹ năng sinh tồn</strong>. Thực tế là, chúng <strong style="color: #00b0f0;">nhận được thức ăn và sự bảo vệ từ nhân viên vườn thú mỗi ngày</strong>. Kết quả là, chúng có thể <strong style="color: #00b0f0;">thấy khó khăn để sinh tồn trong tự nhiên</strong>.<br/><br/>Tóm lại, việc <strong style="color: #ee0000;">nuôi giữ động vật trong vườn thú</strong> có một số <strong style="color: #ee0000;">bất lợi</strong> rõ ràng, như đã đề cập ở trên.',
    'Có một số <strong style="color: #ee0000;">bất lợi</strong> của việc <strong style="color: #ee0000;">nuôi giữ động vật trong vườn thú</strong>.<br/><br/>Một nhược điểm lớn là <strong style="color: #00b0f0;">động vật trong vườn thú thường bị thiếu không gian</strong>. Điều này là do nhiều loài động vật <strong style="color: #00b0f0;">sống trong các khu vực khép kín nhỏ hơn nhiều so với môi trường sống tự nhiên của chúng</strong>. Kết quả là, chúng <strong style="color: #00b0f0;">có thể không thể tự do di chuyển hoặc cư xử một cách tự nhiên</strong>.<br/><br/>Một khía cạnh tiêu cực khác là <strong style="color: #00b0f0;">động vật có thể bị mất tự do</strong>. Điều này có nghĩa là chúng <strong style="color: #00b0f0;">không thể tự chọn nơi sống hoặc tự tìm kiếm thức ăn</strong>. Điều này có thể <strong style="color: #00b0f0;">ảnh hưởng đến sức khỏe và hành vi tự nhiên của chúng</strong>.<br/><br/>Một tác hại nữa là <strong style="color: #00b0f0;">động vật có thể thiếu các kỹ năng sinh tồn</strong>. Bởi vì chúng được con người chăm sóc, chúng <strong style="color: #00b0f0;">không cần phải đi săn hoặc tự bảo vệ mình</strong>. Do đó, chúng có thể <strong style="color: #00b0f0;">thấy khó khăn để sống sót nếu chúng được thả về tự nhiên</strong>.<br/><br/>Tóm lại, việc <strong style="color: #ee0000;">nuôi giữ động vật trong vườn thú</strong> có một số <strong style="color: #ee0000;">bất lợi</strong> rõ ràng, như đã đề cập ở trên.',
    'Các vườn thú thường giữ nhiều loại động vật, chẳng hạn như <strong style="color: #00b0f0;">sư tử</strong>, <strong style="color: #00b0f0;">hổ</strong>, <strong style="color: #00b0f0;">voi</strong>, <strong style="color: #00b0f0;">khỉ</strong>, và <strong style="color: #00b0f0;">gấu</strong>. Một số vườn thú cũng <strong style="color: #00b0f0;">có các loài quý hiếm hoặc có nguy cơ tuyệt chủng</strong>.',
    'Các vườn thú thường <strong style="color: #00b0f0;">giữ rất nhiều loại động vật khác nhau</strong>. Chúng bao gồm <strong style="color: #00b0f0;">sư tử</strong>, <strong style="color: #00b0f0;">hổ</strong>, <strong style="color: #00b0f0;">voi</strong>, <strong style="color: #00b0f0;">khỉ</strong>, và <strong style="color: #00b0f0;">nhiều loài chim</strong>. Một số vườn thú cũng <strong style="color: #00b0f0;">giữ các loài động vật quý hiếm hoặc có nguy cơ tuyệt chủng</strong>.',
    'Các vườn thú có thể giúp <strong style="color: #00b0f0;">bảo vệ các loài động vật có nguy cơ tuyệt chủng</strong>. Chúng cũng <strong style="color: #00b0f0;">cung cấp các cơ hội giáo dục cho du khách</strong>. Kết quả là, mọi người có thể <strong style="color: #00b0f0;">tìm hiểu thêm về động vật hoang dã</strong>.',
    'Các vườn thú có thể giúp <strong style="color: #00b0f0;">bảo vệ các loài có nguy cơ tuyệt chủng thông qua các chương trình bảo tồn</strong>. Chúng cũng <strong style="color: #00b0f0;">cung cấp các cơ hội giáo dục cho du khách</strong>. Thêm vào đó, vườn thú <strong style="color: #00b0f0;">hỗ trợ việc nghiên cứu khoa học về động vật</strong>.',
    'Mọi người nên <strong style="color: #00b0f0;">bảo vệ môi trường sống tự nhiên</strong>. Họ cũng nên <strong style="color: #00b0f0;">tránh săn bắt động vật hoang dã một cách trái phép</strong>. Điều này có thể <strong style="color: #00b0f0;">giúp các quần thể động vật hoang dã sinh tồn và phát triển</strong>.',
    'Mọi người có thể giúp bảo vệ động vật hoang dã bằng cách <strong style="color: #00b0f0;">bảo tồn môi trường sống tự nhiên</strong>. Họ cũng nên <strong style="color: #00b0f0;">tránh mua các sản phẩm làm từ các loài động vật có nguy cơ tuyệt chủng</strong>. Thêm vào đó, việc <strong style="color: #00b0f0;">hỗ trợ các tổ chức bảo tồn</strong> có thể tạo ra sự khác biệt tích cực.'
]

levels = re.split(r'(<div class="translation-text"[^>]*>)', content)
# levels length should be 2 + 22*2 = 46. Let's process safely
new_html = levels[0]

count = 0
for i in range(1, len(levels), 2):
    tag = levels[i]
    rest = levels[i+1]
    
    parts = rest.split('</div>', 1)
    if len(parts) > 1 and count < len(new_translations):
        new_html += tag + new_translations[count] + '</div>' + parts[1]
        count += 1
    else:
        new_html += tag + rest

with open(path, 'w', encoding='utf-8') as f:
    f.write(new_html)

print(f"Replaced {count} translations in test 3.")
